"""initial_schema

Revision ID: d4d78ec3ccc6
Revises: None
Create Date: 2026-06-04 01:25:18.385797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d78ec3ccc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_id', sa.String(length=36), nullable=False))
    op.add_column('events', sa.Column('visitor_id', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('dwell_ms', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('is_staff', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('metadata', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=True)
    op.create_index(op.f('ix_events_visitor_id'), 'events', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_visitor_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_column('events', 'metadata')
    op.drop_column('events', 'confidence')
    op.drop_column('events', 'is_staff')
    op.drop_column('events', 'dwell_ms')
    op.drop_column('events', 'visitor_id')
    op.drop_column('events', 'event_id')
    # ### end Alembic commands ###
